name: 限制时间段禁止合并 PR

# 触发工作流的事件
on:
  pull_request:
    types: [opened, synchronize, reopened]

# 为工作流设置默认权限，checks:write 是创建状态检查所必需的
permissions:
  checks: write

jobs:
  block-merge-in-window:
    runs-on: ubuntu-latest
    name: 'Block Merge Window Check'

    steps:
      # 步骤 1: 检查当前是否在允许的时间窗口内
      - name: 'Check current time window'
        id: time_check # 为此步骤设置一个 ID，方便后续步骤引用其输出
        run: |
          now_utc=$(date -u +"%H:%M")
          weekday=$(date -u +"%u")  # 1=星期一 ... 7=星期日
          
          # 设置允许合并的时间窗口 (UTC 时间)
          # 北京时间周日 12:30 对应 UTC 周日 04:30
          # 北京时间周日 22:00 对应 UTC 周日 14:00
          start="04:30"
          end="14:00"

          in_window=false
          if [ "$weekday" -eq "7" ] && [[ "$now_utc" > "$start" && "$now_utc" < "$end" ]]; then
            in_window=true
          fi
          
          echo "Current UTC time: $now_utc on weekday $weekday"
          echo "Is in merge window: $in_window"
          
          # 将结果作为输出，供后续步骤使用
          echo "in_window=$in_window" >> $GITHUB_OUTPUT

      # 步骤 2: 如果在时间窗口内，则创建“成功”状态
      - name: 'Allow Merge (In Window)'
        # 条件：仅当上一步的输出 in_window 为 'true' 时运行
        if: steps.time_check.outputs.in_window == 'true'
        uses: actions/github-script@v7 # 建议使用最新的主版本 v7
        with:
          # 使用你仓库中存储的 ORG_TOKEN
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Merge Window Check", // 状态检查的名称
              head_sha: context.payload.pull_request.head.sha,
              status: "completed",
              conclusion: "success",
              output: {
                title: "✅ 允许合并",
                summary: "当前时间在允许合并的时间窗口内。"
              }
            });

      # 步骤 3: 如果不在时间窗口内，则创建“失败”状态
      - name: 'Block Merge (Outside Window)'
        # 条件：仅当上一步的输出 in_window 为 'false' 时运行
        if: steps.time_check.outputs.in_window == 'false'
        uses: actions/github-script@v7
        with:
          # 同样使用 ORG_TOKEN
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Merge Window Check", // 状态检查的名称必须与上面保持一致
              head_sha: context.payload.pull_request.head.sha,
              status: "completed",
              conclusion: "failure",
              output: {
                title: "❌ 禁止合并",
                summary: "当前时间不在允许合并的时间窗口内 (UTC 周日 04:30 - 14:00)。"
              }
            });
