name: 限制时间段禁止合并 PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  block-merge-in-window:
    runs-on: ubuntu-latest

    steps:
      - name: Determine if we're in the restricted window
        id: timecheck
        run: |
          now_utc=$(date -u +"%H:%M")
          weekday=$(date -u +"%u")   # 1=Mon ... 7=Sun
          start="04:30"  # UTC 时间，北京时间周日12:30
          end="14:00"    # UTC 时间，北京时间周日22:00
          in_window=false
          if [ "$weekday" -eq "7" ] && [[ "$now_utc" > "$start" && "$now_utc" < "$end" ]]; then
            in_window=true
          fi
          echo "in_window=$in_window" >> $GITHUB_OUTPUT
          echo "now_utc=$now_utc, weekday=$weekday"

      - name: Create check run to block merge if in restricted window
        if: steps.timecheck.outputs.in_window == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            await github.checks.create({
              owner,
              repo,
              name: "Merge Block Check",
              head_sha: context.payload.pull_request.head.sha,
              status: "completed",
              conclusion: "failure",
              output: {
                title: "禁止合并",
                summary: "当前时间为北京时间周日 12:30–22:00，禁止合并此 PR。请在允许时间后再试。"
              }
            });

      - name: Create check run to allow merge if not in restricted window
        if: steps.timecheck.outputs.in_window != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            await github.checks.create({
              owner,
              repo,
              name: "Merge Block Check",
              head_sha: context.payload.pull_request.head.sha,
              status: "completed",
              conclusion: "success",
              output: {
                title: "允许合并",
                summary: "当前时间允许合并此 PR。"
              }
            });
