name: 限制时间段禁止合并 PR

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
  workflow_dispatch:

permissions:
  contents: read  # 根据你 token 权限调整

jobs:
  block-merge-in-window:
    runs-on: ubuntu-latest

    steps:
      - name: 判断是否在禁止合并时间段（北京时间周日 12:30–22:00）
        id: timecheck
        run: |
          now_utc=$(date -u +"%H:%M")
          weekday=$(date -u +"%u")  # 1=Mon ... 7=Sun
          start="04:30"            # UTC 对应北京时间周日12:30
          end="14:00"              # UTC 对应北京时间周日22:00
          in_window=false
          if [ "$weekday" -eq "7" ] && [[ "$now_utc" > "$start" && "$now_utc" < "$end" ]]; then
            in_window=true
          fi
          echo "in_window=$in_window" >> $GITHUB_OUTPUT

      - name: 禁止合并：创建失败状态检查
        if: steps.timecheck.outputs.in_window == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = pr.head.sha;

            await github.rest.checks.create({
              owner,
              repo,
              name: "Merge Block Check",
              head_sha: sha,
              status: "completed",
              conclusion: "failure",
              output: {
                title: "禁止合并",
                summary: "当前为北京时间周日 12:30–22:00，禁止合并此 PR。请在允许时间后再试。"
              }
            });

      - name: 允许合并：创建成功状态检查
        if: steps.timecheck.outputs.in_window != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = pr.head.sha;

            await github.rest.checks.create({
              owner,
              repo,
              name: "Merge Block Check",
              head_sha: sha,
              status: "completed",
              conclusion: "success",
              output: {
                title: "允许合并",
                summary: "当前时间允许合并此 PR。"
              }
            });
