name: PR 时间窗合并限制

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  block-merge-in-window:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: 获取当前 UTC 时间和星期
        id: timecheck
        run: |
          now_utc=$(date -u +"%H:%M")
          weekday=$(date -u +"%u")  # 1=Mon, ..., 7=Sun
          start="04:30"  # UTC == 北京时间周日12:30
          end="14:00"    # UTC == 北京时间周日22:00
          in_window=false
          if [ "$weekday" -eq "7" ] && [[ "$now_utc" > "$start" && "$now_utc" < "$end" ]]; then
            in_window=true
          fi
          echo "in_window=$in_window" >> $GITHUB_OUTPUT

      - name: 设置 PR 合并状态检查
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = pr.head.sha;
            const inWindow = "${{ steps.timecheck.outputs.in_window }}" === "true";

            await github.rest.checks.create({
              owner,
              repo,
              name: "PR Merge Blocker",
              head_sha: sha,
              status: "completed",
              conclusion: inWindow ? "failure" : "success",
              output: {
                title: inWindow
                  ? "❌ 当前为禁止提交 PR 的时间窗口（北京时间周日 12:30–22:00）"
                  : "✅ PR 合规提交时间",
                summary: inWindow
                  ? "本次 PR 提交时间违反团队规则，将被阻止合并。"
                  : "提交时间符合规范，可以继续审查与合并。"
              }
            });
