name: PR Time Window Status Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  pr-time-window-check:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if current time is in restricted window
        id: timecheck
        run: |
          now_utc=$(date -u +"%H:%M")
          weekday=$(date -u +"%u")   # 1=Mon ... 7=Sun
          start="04:30"  # UTC time for Beijing Sunday 12:30
          end="14:00"    # UTC time for Beijing Sunday 22:00
          echo "Current UTC time: $now_utc"
          in_window=false
          if [ "$weekday" -eq "7" ] && [[ "$now_utc" > "$start" && "$now_utc" < "$end" ]]; then
            in_window=true
          fi
          echo "in_window=$in_window" >> $GITHUB_OUTPUT

      - name: Set PR status check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          in_window="${{ steps.timecheck.outputs.in_window }}"
          conclusion="success"
          description="PR 合规提交时间 ✅"

          if [ "$in_window" = "true" ]; then
            conclusion="failure"
            description="❌ 当前为禁止提交 PR 的时间窗口（北京时间周日 12:30–22:00）"
          fi

          gh api repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -f state="$conclusion" \
            -f context="PR Time Window Check" \
            -f description="$description"
