name: 将笔记同步到博客

on:
  push:
    branches: [main]
    paths: ['Note/**']
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出目标仓库 QFNU-PCT.github.io（注意：默认是当前工作目录）
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: QFNU-PCT/QFNU-PCT.github.io
          token: ${{ secrets.BLOG_ACCESS_TOKEN }}

      # 2. 下载源仓库 Note 中的 Note 目录
      - name: Download Source Files
        env:
          SOURCE_REPO: "https://github.com/QFNU-PCT/Note"
        run: |
          curl -L -H "Authorization: token ${{ secrets.BLOG_ACCESS_TOKEN }}" \
            -o note-files.zip "${{ env.SOURCE_REPO }}/archive/main.zip?path=Note"
          unzip -q note-files.zip "*/Note/*" -d temp-dir
          mkdir -p source/_posts
          cp -r temp-dir/*/Note/* source/_posts/
          rm -rf note-files.zip temp-dir

      # 3. 配置 Git 并推送更改（使用 Token 身份）
      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.BLOG_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add source/_posts
          if git diff-index --quiet HEAD --; then
            echo "No changes detected."
          else
            git commit -m "Auto-sync notes from Note repo"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/QFNU-PCT/QFNU-PCT.github.io.git
            git push origin main
          fi
